### ISSUE TITLE
Not working in NodeJS v18.0.0

### ISSUE THREAD

**Issue by artheus** [bcoe/c8#401]
* **Version**: 7.11.0
* **Node version**: 18.0.0
* **Platform**:  Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

```json
# package.json
{
  "...": "...",
  "scripts": {
    "test": "mocha test --recursive",
    "test:coverage": "nyc npm test",
    "build": "tsc -p .",
  },
  "dependencies": {
    "@testdeck/mocha": "^0.2.0",
    "@types/chai": "^4.3.1",
    "@types/deep-equal": "1.0.1",
    "@types/mocha": "9.1.1",
    "@types/node": "^17.0.23",
    "@types/node-fetch": "^2.6.1",
    "@types/yargs": "^17.0.10",
    "c8": "^7.11.0",
    "c8-as-nyc": "1.0.4",
    "chai": "^4.3.6",
    "chalk": "4.1.2",
    "deep-equal": "2.0.5",
    "handlebars": "^4.7.7",
    "mocha": "^9.2.2",
    "node-fetch": "^2.6.6",
    "pkg": "5.6.0",
    "source-map-support": "^0.5.21",
    "sync-fetch": "0.3.1",
    "ts-mocha": "9.0.2",
    "ts-mockito": "^2.6.1",
    "ts-node": "^10.7.0",
    "typescript": "^4.6.3",
    "uuid": "7.0.3",
    "yaml": "2.0.1",
    "yargs": "^17.4.1"
  },
  "devDependencies": {
    "mocha-junit-reporter": "2.0.2",
    "mocha-multi-reporters": "1.5.1",
    "nock": "13.2.4"
  }
}
```

```json
# tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": ["es6", "es2015", "dom"],
    "declaration": true,
    "outDir": "build",
    "baseUrl": "./",
    "rootDir": ".",
    "strict": true,
    "typeRoots": ["node_modules/@types"],
    "types": ["node", "mocha"],
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "experimentalDecorators": true
  },
  "include": [
    "src/**/*.ts"
  ]
}
```

```json
# .nycrc.json
{
  "extends": "@istanbuljs/nyc-config-typescript",
  "include": [
    "src/**/*"
  ],
  "extension": [".ts"],
  "exclude": [
    "src/test/decorators/**",
    "src/app.ts"
  ],
  "reporter": [
    "text",
    "cobertura",
    "lcov",
    "lcovonly"
  ],
  "check-coverage": false
}
```

```yaml
# .mocharc.yml
require: ['ts-node/register/transpile-only', 'source-map-support/register']
reporter: mocha-multi-reporters
reporter-option:
  - 'configFile=.mochamulti.json'
recursive: true
color: true
exit: true
'check-leaks': true
diff: true
'full-trace': true
ui: 'bdd'
extension: ['ts', 'test.ts']
ignore: ['src/app.ts']
spec: "test"
```

```json
# .mochamulti.json
{
  "reporterEnabled": "spec, mocha-junit-reporter"
}
```

running the tests with `npm run test` gives me:
```
.... lots of test output .... 
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
```

in node 16 and 17 this has worked well, giving me proper code coverage output.
upgrading to node 18, this no longer gives any coverage at all.
